### ISSUE TITLE
"Exception: Bot RTM connection failed. Invalid Slack bot token?" on new installs

### ISSUE THREAD

**Issue by noisymime** [pR0Ps/slack-read-only-bot#1]
Firstly thanks for this updated version of the read-only bot!

I ran into an issue with it however where attempting to run it with a new legacy app results in:
```
Traceback (most recent call last):
  File "/app/slack_read_only_bot.py", line 134, in <module>
    main()
  File "/app/slack_read_only_bot.py", line 130, in main
    ReadOnlyBot(**yaml.safe_load(args.config.read())).run()
  File "/app/slack_read_only_bot.py", line 35, in __init__
    raise Exception("Bot RTM connection failed. Invalid Slack bot token?")
Exception: Bot RTM connection failed. Invalid Slack bot token?
```

Turns out that the `rtm.start` method is no longer available to newly created Slack apps. See: https://github.com/slackapi/python-slack-sdk/issues/1190

Solution is to change line 34 (https://github.com/pR0Ps/slack-read-only-bot/blob/master/slack_read_only_bot.py#L34) from:
`if not self.slack_bot.rtm_connect():`
to
`if not self.slack_bot.rtm_connect(with_team_state=False):`

This will then connect and work fine. 

I can submit a PR to fix this if that's easier.

**Comment by pR0Ps** [comment]
Applied, thanks for the heads up!
